---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_facts["swaptotal_mb"] > 0
  changed_when: true

- name: Disable swap permanently in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s+.*)$'
    replace: '# \1'
    backup: true

- name: Configure required kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/kubernetes.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      overlay
      br_netfilter

- name: Load overlay kernel module
  ansible.builtin.command: modprobe overlay
  changed_when: false

- name: Load br_netfilter kernel module
  ansible.builtin.command: modprobe br_netfilter
  changed_when: false

- name: Configure Kubernetes sysctl settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  notify: Reload sysctl
